export enum ModalPurpose {
  ADD_RESTAURANT = "ADD_RESTAURANT",
  CREATE_VIEW = "CREATE_VIEW",
  ADD_ELEMENT = "ADD_ELEMENT",
  ADMIN_EDIT_ELEMENT = "ADMIN_EDIT_ELEMENT",
  RESTAURANT_EDIT_ELEMENT = "RESTAURANT_EDIT_ELEMENT",
  COLOR = "COLOR",
}
